### ISSUE TITLE
After finishing the Knit operation, the FSM should enter state Init not state Ready

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-firmware#173]

**Comment by X-sam** [comment]
Is this related to AllYarnsAreBeautiful/ayab-desktop#577

**Comment by jonathanperret** [comment]
@X-sam I'd say they're not really related. https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/577 is about canceling, whereas this issue is about the normal end of knitting, and the linked PR (#174) changes the `Knitter::stopKnitting` method which is only called at the end of a complete knitting run.

In any case #174 does make the change requested here, I think this can be closed.
